#!/bin/bash

set -e

TINY=zppz/tiny:21.01.02
cmd_find="$(docker run --rm ${TINY} cat /usr/tools/find-image)"
MINI=$(bash -c "${cmd_find}" -- zppz/mini)
cmd_build="$(docker run --rm ${MINI} cat /usr/tools/build-docker)"
PARENT=$(bash -c "${cmd_find}" -- zppz/py3)

bash -c "${cmd_build}" -- --build-arg PARENT=${PARENT} $@

